remote_theme: MicrosoftLearning/Jekyll-Theme
exclude:
  - readme.md
  - .github/
  - Labfiles/
  - tools/
  - Instructions/Consolidated/
  - workshop.md
  - explore.md
  - labs.json
header_pages:
  - index.html
author: FelipePorcinoProfessor
twitter_username: mslearning
github_username: FelipePorcinoProfessor
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable: true
title: Exercícios de AI Agents em Português
